### ISSUE TITLE
Handle exception for missing mana symbol

### ISSUE THREAD

**Issue by StephenGibbsDev** [StephenGibbsDev/MTGCore#41]
![image](https://user-images.githubusercontent.com/44094125/118500429-b09ed300-b71f-11eb-94e6-8ebb1702fff4.png)

Handle above exception more gracefully as well as displaying which card it broke on.

**Comment by ConnorDownes** [comment]
I've put in a PR to ensure the exception will be thrown properly (with an error message shown on the frontend).

If the desired behaviour is to gracefully handle the exception then I can pick this up tomorrow.

**Comment by ConnorDownes** [comment]
https://github.com/StephenGibbsDev/MTGCore/pull/46
