### ISSUE TITLE
Decrease card size / put it in collapsible element

### ISSUE THREAD

**Issue by StephenGibbsDev** [StephenGibbsDev/MTGCore#61]
Card image looks really cool however I would probably scale down the image slightly and move the card description / info to the right.
Its up to you how you do this but i dont think its that good only having 2 cards on display at a time.
![image](https://user-images.githubusercontent.com/44094125/119524936-fd188d00-bd75-11eb-800d-bada93781a8a.png)

_Originally posted by @StephenGibbsDev in https://github.com/StephenGibbsDev/MTGCore/pull/55#discussion_r638908922_

**Comment by ConnorDownes** [comment]
Completed in [PR #67](https://github.com/StephenGibbsDev/MTGCore/pull/67)
